SELECT * FROM users WHERE EMAIL IS NULL;
SELECT * FROM users WHERE EMAIL IS NOT NULL;
SELECT * FROM users WHERE EMAIL IS NOT NULL AND age = 30;

SELECT name, surname, IFNULL(age, 0) AS age FROM users;
